project_id = "plnphgdrawpsnumnejzc"

[functions.test-trustpilot]
verify_jwt = false

[functions.hotel-meta-search]
verify_jwt = false

[functions.google-hotel-reviews]
verify_jwt = false

[functions.business-search]
verify_jwt = false

[functions.manage-affiliate-user]
verify_jwt = false

[functions.batch-fetch-reviews]
verify_jwt = false

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.voice-search-intent]
verify_jwt = false