/**
 * Reads scripts/blog-articles.extracted.json and emits a single SQL file
 * scripts/blog-articles.import.sql that UPSERTs each article into
 * public.blog_posts (FR columns only; EN/AR translation later).
 *
 * Run: bun run scripts/build-blog-import-sql.ts
 */
import * as fs from "node:fs";

type Extracted = {
  slug: string;
  template: "article_template" | "custom";
  sort_order: number;
  entries: any[] | null;
  props: Record<string, any>;
  customHeroUrl: string | null;
};

const data: Extracted[] = JSON.parse(fs.readFileSync("scripts/blog-articles.extracted.json", "utf8"));

// Use $$-quoting for postgres. Random tag to avoid collisions.
function dq(value: string, tag = "BLOG"): string {
  // ensure tag not present in value
  let t = tag;
  let i = 0;
  while (value.includes(`$${t}$`)) t = `${tag}${++i}`;
  return `$${t}$${value}$${t}$`;
}
function nullable(v: any): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "string") return dq(v);
  return "NULL";
}
function jsonbOrNull(v: any): string {
  if (!v) return "NULL";
  return `${dq(JSON.stringify(v))}::jsonb`;
}

const stmts: string[] = [];
stmts.push("-- Auto-generated by scripts/build-blog-import-sql.ts");
stmts.push("BEGIN;");

for (const a of data) {
  const p = a.props ?? {};
  const title = typeof p.articleTitle === "string" ? p.articleTitle : a.slug;
  const description = typeof p.articleDescription === "string" ? p.articleDescription : null;
  const heroTop = typeof p.heroTitleTop === "string" ? p.heroTitleTop : null;
  const heroBottom = typeof p.heroTitleBottom === "string" ? p.heroTitleBottom : null;
  const heroSubtitle = typeof p.heroSubtitle === "string" ? p.heroSubtitle : null;
  const intro = typeof p.intro === "string" ? p.intro : null;
  const heroAlt = typeof p.heroAlt === "string" ? p.heroAlt : null;
  const bookmarkSlug = typeof p.bookmarkSlug === "string" ? p.bookmarkSlug : a.slug;
  const datePublished = typeof p.datePublished === "string" ? p.datePublished : null;

  stmts.push(`
INSERT INTO public.blog_posts (
  slug, template, sort_order, is_published, published_at,
  title_fr, content_fr,
  entries_fr,
  hero_title_top_fr, hero_title_bottom_fr, hero_subtitle_fr, intro_fr,
  hero_alt, bookmark_slug, custom_hero_image_url
) VALUES (
  ${dq(a.slug)},
  ${dq(a.template)},
  ${a.sort_order},
  TRUE,
  ${datePublished ? dq(datePublished) + "::timestamptz" : "now()"},
  ${dq(title)},
  ${nullable(description)},
  ${jsonbOrNull(a.entries)},
  ${nullable(heroTop)},
  ${nullable(heroBottom)},
  ${nullable(heroSubtitle)},
  ${nullable(intro)},
  ${nullable(heroAlt)},
  ${dq(bookmarkSlug)},
  ${nullable(a.customHeroUrl)}
)
ON CONFLICT (slug) DO UPDATE SET
  template = EXCLUDED.template,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published,
  published_at = COALESCE(public.blog_posts.published_at, EXCLUDED.published_at),
  title_fr = EXCLUDED.title_fr,
  content_fr = EXCLUDED.content_fr,
  entries_fr = EXCLUDED.entries_fr,
  hero_title_top_fr = EXCLUDED.hero_title_top_fr,
  hero_title_bottom_fr = EXCLUDED.hero_title_bottom_fr,
  hero_subtitle_fr = EXCLUDED.hero_subtitle_fr,
  intro_fr = EXCLUDED.intro_fr,
  hero_alt = EXCLUDED.hero_alt,
  bookmark_slug = EXCLUDED.bookmark_slug,
  custom_hero_image_url = EXCLUDED.custom_hero_image_url,
  updated_at = now();
`);
}

stmts.push("COMMIT;");
fs.writeFileSync("scripts/blog-articles.import.sql", stmts.join("\n"));
console.log(`Wrote scripts/blog-articles.import.sql (${stmts.length - 2} upserts)`);
