/**
 * Registre d'icônes du moteur Storyboard — GÉNÉRÉ (node /tmp/gen-icons.mjs).
 * Source unique : src/lib/videoIconCatalog.ts. Imports nommés = tree-shaking.
 */
import React from "react";
import type { IconType } from "react-icons";
import { FaHandHoldingHeart, FaHotel, FaTaxi } from "react-icons/fa6";
import { TbAirBalloon, TbArrowRight, TbArtboard, TbBabyCarriage, TbBackpack, TbBarbell, TbBath, TbBeach, TbBed, TbBellRinging, TbBike, TbBinoculars, TbBook2, TbBottle, TbBriefcase, TbBrush, TbBuildingBank, TbBuildingCastle, TbBuildingMonument, TbBuildingMosque, TbBuildingPavilion, TbBuildingSkyscraper, TbBuildingStore, TbBus, TbCactus, TbCake, TbCalendarCheck, TbCamera, TbCar, TbClock24, TbCoffee, TbConfetti, TbCooker, TbCreditCard, TbDeviceLaptop, TbDeviceMobile, TbDeviceProjector, TbDiamond, TbDisc, TbDog, TbDrone, TbDroplet, TbDropletFilled, TbExternalLink, TbFlower, TbFriends, TbGift, TbGlassChampagne, TbGlassCocktail, TbGlassFull, TbGolf, TbHeadset, TbHeartFilled, TbHeartHandshake, TbHorseToy, TbHotelService, TbLanguage, TbLeaf, TbLeaf2, TbLuggage, TbMail, TbMapPin, TbMassage, TbMicrophone, TbMicrophone2, TbMoodSmile, TbMoonStars, TbMotorbike, TbMountain, TbMusic, TbPanoramaHorizontal, TbParking, TbParkingCircle, TbPhone, TbPlane, TbPlaneDeparture, TbPlant2, TbPlayCard, TbPresentation, TbQrcode, TbRecycle, TbRoute, TbRun, TbSailboat, TbScubaMask, TbSearch, TbShare2, TbShieldCheck, TbShirt, TbShoppingBag, TbSoccerField, TbSolarPanel, TbSoup, TbSparkles, TbSpeakerphone, TbStarFilled, TbSteeringWheel, TbSun, TbSunset, TbSunset2, TbSwimming, TbTargetArrow, TbTent, TbTexture, TbTheater, TbTicket, TbToolsKitchen, TbToolsKitchen2, TbTrain, TbTrees, TbTruckDelivery, TbUsers, TbUsersGroup, TbVideo, TbWheelchair, TbWifi, TbYoga } from "react-icons/tb";
import { MdOutlineCelebration, MdOutlineHiking, MdOutlineKitesurfing, MdOutlineNightlife, MdOutlinePool, MdOutlineRoomService, MdOutlineSelfImprovement, MdOutlineSpa, MdOutlineSportsGolf, MdOutlineSportsTennis, MdOutlineSurfing, MdOutlineTerrain, MdRestaurantMenu } from "react-icons/md";
import { SiAirbnb, SiApple, SiBookingdotcom, SiFacebook, SiGoogle, SiInstagram, SiTiktok, SiTripadvisor, SiWhatsapp, SiYoutube } from "react-icons/si";

export const STORYBOARD_ICONS: Record<string, IconType> = {
  "fa6:FaHandHoldingHeart": FaHandHoldingHeart,
  "fa6:FaHotel": FaHotel,
  "fa6:FaTaxi": FaTaxi,
  "tb:TbAirBalloon": TbAirBalloon,
  "tb:TbArrowRight": TbArrowRight,
  "tb:TbArtboard": TbArtboard,
  "tb:TbBabyCarriage": TbBabyCarriage,
  "tb:TbBackpack": TbBackpack,
  "tb:TbBarbell": TbBarbell,
  "tb:TbBath": TbBath,
  "tb:TbBeach": TbBeach,
  "tb:TbBed": TbBed,
  "tb:TbBellRinging": TbBellRinging,
  "tb:TbBike": TbBike,
  "tb:TbBinoculars": TbBinoculars,
  "tb:TbBook2": TbBook2,
  "tb:TbBottle": TbBottle,
  "tb:TbBriefcase": TbBriefcase,
  "tb:TbBrush": TbBrush,
  "tb:TbBuildingBank": TbBuildingBank,
  "tb:TbBuildingCastle": TbBuildingCastle,
  "tb:TbBuildingMonument": TbBuildingMonument,
  "tb:TbBuildingMosque": TbBuildingMosque,
  "tb:TbBuildingPavilion": TbBuildingPavilion,
  "tb:TbBuildingSkyscraper": TbBuildingSkyscraper,
  "tb:TbBuildingStore": TbBuildingStore,
  "tb:TbBus": TbBus,
  "tb:TbCactus": TbCactus,
  "tb:TbCake": TbCake,
  "tb:TbCalendarCheck": TbCalendarCheck,
  "tb:TbCamera": TbCamera,
  "tb:TbCar": TbCar,
  "tb:TbClock24": TbClock24,
  "tb:TbCoffee": TbCoffee,
  "tb:TbConfetti": TbConfetti,
  "tb:TbCooker": TbCooker,
  "tb:TbCreditCard": TbCreditCard,
  "tb:TbDeviceLaptop": TbDeviceLaptop,
  "tb:TbDeviceMobile": TbDeviceMobile,
  "tb:TbDeviceProjector": TbDeviceProjector,
  "tb:TbDiamond": TbDiamond,
  "tb:TbDisc": TbDisc,
  "tb:TbDog": TbDog,
  "tb:TbDrone": TbDrone,
  "tb:TbDroplet": TbDroplet,
  "tb:TbDropletFilled": TbDropletFilled,
  "tb:TbExternalLink": TbExternalLink,
  "tb:TbFlower": TbFlower,
  "tb:TbFriends": TbFriends,
  "tb:TbGift": TbGift,
  "tb:TbGlassChampagne": TbGlassChampagne,
  "tb:TbGlassCocktail": TbGlassCocktail,
  "tb:TbGlassFull": TbGlassFull,
  "tb:TbGolf": TbGolf,
  "tb:TbHeadset": TbHeadset,
  "tb:TbHeartFilled": TbHeartFilled,
  "tb:TbHeartHandshake": TbHeartHandshake,
  "tb:TbHorseToy": TbHorseToy,
  "tb:TbHotelService": TbHotelService,
  "tb:TbLanguage": TbLanguage,
  "tb:TbLeaf": TbLeaf,
  "tb:TbLeaf2": TbLeaf2,
  "tb:TbLuggage": TbLuggage,
  "tb:TbMail": TbMail,
  "tb:TbMapPin": TbMapPin,
  "tb:TbMassage": TbMassage,
  "tb:TbMicrophone": TbMicrophone,
  "tb:TbMicrophone2": TbMicrophone2,
  "tb:TbMoodSmile": TbMoodSmile,
  "tb:TbMoonStars": TbMoonStars,
  "tb:TbMotorbike": TbMotorbike,
  "tb:TbMountain": TbMountain,
  "tb:TbMusic": TbMusic,
  "tb:TbPanoramaHorizontal": TbPanoramaHorizontal,
  "tb:TbParking": TbParking,
  "tb:TbParkingCircle": TbParkingCircle,
  "tb:TbPhone": TbPhone,
  "tb:TbPlane": TbPlane,
  "tb:TbPlaneDeparture": TbPlaneDeparture,
  "tb:TbPlant2": TbPlant2,
  "tb:TbPlayCard": TbPlayCard,
  "tb:TbPresentation": TbPresentation,
  "tb:TbQrcode": TbQrcode,
  "tb:TbRecycle": TbRecycle,
  "tb:TbRoute": TbRoute,
  "tb:TbRun": TbRun,
  "tb:TbSailboat": TbSailboat,
  "tb:TbScubaMask": TbScubaMask,
  "tb:TbSearch": TbSearch,
  "tb:TbShare2": TbShare2,
  "tb:TbShieldCheck": TbShieldCheck,
  "tb:TbShirt": TbShirt,
  "tb:TbShoppingBag": TbShoppingBag,
  "tb:TbSoccerField": TbSoccerField,
  "tb:TbSolarPanel": TbSolarPanel,
  "tb:TbSoup": TbSoup,
  "tb:TbSparkles": TbSparkles,
  "tb:TbSpeakerphone": TbSpeakerphone,
  "tb:TbStarFilled": TbStarFilled,
  "tb:TbSteeringWheel": TbSteeringWheel,
  "tb:TbSun": TbSun,
  "tb:TbSunset": TbSunset,
  "tb:TbSunset2": TbSunset2,
  "tb:TbSwimming": TbSwimming,
  "tb:TbTargetArrow": TbTargetArrow,
  "tb:TbTent": TbTent,
  "tb:TbTexture": TbTexture,
  "tb:TbTheater": TbTheater,
  "tb:TbTicket": TbTicket,
  "tb:TbToolsKitchen": TbToolsKitchen,
  "tb:TbToolsKitchen2": TbToolsKitchen2,
  "tb:TbTrain": TbTrain,
  "tb:TbTrees": TbTrees,
  "tb:TbTruckDelivery": TbTruckDelivery,
  "tb:TbUsers": TbUsers,
  "tb:TbUsersGroup": TbUsersGroup,
  "tb:TbVideo": TbVideo,
  "tb:TbWheelchair": TbWheelchair,
  "tb:TbWifi": TbWifi,
  "tb:TbYoga": TbYoga,
  "md:MdOutlineCelebration": MdOutlineCelebration,
  "md:MdOutlineHiking": MdOutlineHiking,
  "md:MdOutlineKitesurfing": MdOutlineKitesurfing,
  "md:MdOutlineNightlife": MdOutlineNightlife,
  "md:MdOutlinePool": MdOutlinePool,
  "md:MdOutlineRoomService": MdOutlineRoomService,
  "md:MdOutlineSelfImprovement": MdOutlineSelfImprovement,
  "md:MdOutlineSpa": MdOutlineSpa,
  "md:MdOutlineSportsGolf": MdOutlineSportsGolf,
  "md:MdOutlineSportsTennis": MdOutlineSportsTennis,
  "md:MdOutlineSurfing": MdOutlineSurfing,
  "md:MdOutlineTerrain": MdOutlineTerrain,
  "md:MdRestaurantMenu": MdRestaurantMenu,
  "si:SiAirbnb": SiAirbnb,
  "si:SiApple": SiApple,
  "si:SiBookingdotcom": SiBookingdotcom,
  "si:SiFacebook": SiFacebook,
  "si:SiGoogle": SiGoogle,
  "si:SiInstagram": SiInstagram,
  "si:SiTiktok": SiTiktok,
  "si:SiTripadvisor": SiTripadvisor,
  "si:SiWhatsapp": SiWhatsapp,
  "si:SiYoutube": SiYoutube,
};

export const resolveStoryboardIcon = (key: string | null | undefined): IconType | null =>
  key && STORYBOARD_ICONS[key] ? STORYBOARD_ICONS[key] : null;
