// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/search-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { z } from "npm:zod@^4.3.6";
var SUPABASE_URL = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var search_businesses_default = defineTool({
  name: "search_businesses",
  title: "Search One World Morocco businesses",
  description: "Search the public One World Morocco catalog of curated businesses (restaurants, hotels, riads, activities, boutiques) in Marrakech, Essaouira and across Morocco. Returns name, city, category, rating, price range, hook description and public URL.",
  inputSchema: {
    query: z.string().min(1).describe("Free-text search: a name, cuisine, activity, neighborhood, e.g. 'rooftop marrakech', 'riad essaouira', 'couscous'."),
    city: z.string().optional().describe("Optional city filter, e.g. 'Marrakech', 'Essaouira'."),
    category: z.string().optional().describe("Optional main category filter, e.g. 'Restaurant', 'Hotel', 'Activity'."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results to return (1-20, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, category, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("businesses").select(
      "id, name, slug, main_category, city, neighborhood, hook_fr, hook_en, computed_rating, total_review_count, min_price, manual_price_range, priority_score"
    ).eq("is_active", true).or(
      `name.ilike.%${query}%,description.ilike.%${query}%,keywords.ilike.%${query}%,categories.ilike.%${query}%`
    ).order("priority_score", { ascending: false, nullsFirst: false }).limit(Math.min(limit ?? 10, 20));
    if (city) q = q.ilike("city", `%${city}%`);
    if (category) q = q.ilike("main_category", `%${category}%`);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const results = (data ?? []).map((b) => ({
      name: b.name,
      city: b.city,
      neighborhood: b.neighborhood,
      category: b.main_category,
      rating: b.computed_rating,
      review_count: b.total_review_count,
      price_range: b.manual_price_range ?? (b.min_price ? `from ${b.min_price} MAD` : null),
      hook: b.hook_fr ?? b.hook_en,
      url: b.slug ? `https://oneworldmorocco.com/${b.slug}` : null
    }));
    return {
      content: [
        {
          type: "text",
          text: results.length ? JSON.stringify(results, null, 2) : "No businesses found for this query."
        }
      ],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-business.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z2 } from "npm:zod@^4.3.6";
var SUPABASE_URL2 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var get_business_default = defineTool2({
  name: "get_business",
  title: "Get One World Morocco business details",
  description: "Fetch the full public details of a single One World Morocco business by its slug (from the URL, e.g. 'dar-fragrance'). Returns description, address, phone, website, hours, ratings, prices and social links.",
  inputSchema: {
    slug: z2.string().min(1).describe("Business slug from the oneworldmorocco.com URL, e.g. 'dar-fragrance'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_ANON_KEY2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("businesses").select(
      "name, slug, main_category, categories, city, neighborhood, address, phone, whatsapp, email, website, description, hook_fr, hook_en, opening_hours, computed_rating, total_review_count, min_price, manual_price_range, languages, booking_url, reserve_now_url, menu_url, instagram_url, facebook_url, tripadvisor_url"
    ).eq("slug", slug).eq("is_active", true).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No business found with slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { business: { ...data, url: `https://oneworldmorocco.com/${data.slug}` } }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "one-world-morocco",
  title: "One World Morocco",
  version: "0.1.0",
  instructions: "Public read-only access to the One World Morocco catalog: curated restaurants, hotels, riads, activities and boutiques in Marrakech, Essaouira and across Morocco. Use `search_businesses` to find places (by name, cuisine, activity, city, neighborhood) and `get_business` to fetch full details of one place by its slug. All data is public \u2014 no personal or member data is exposed.",
  tools: [search_businesses_default, get_business_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
