// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/search-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { z } from "npm:zod@^4.3.6";
var SUPABASE_URL = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var search_businesses_default = defineTool({
  name: "search_businesses",
  title: "Search One World Morocco businesses",
  description: "Search the public One World Morocco catalog of curated businesses (restaurants, hotels, riads, activities, boutiques) in Marrakech, Essaouira and across Morocco. Returns name, city, category, rating, price range, hook description and public URL.",
  inputSchema: {
    query: z.string().min(1).describe("Free-text search: a name, cuisine, activity, neighborhood, e.g. 'rooftop marrakech', 'riad essaouira', 'couscous'."),
    city: z.string().optional().describe("Optional city filter, e.g. 'Marrakech', 'Essaouira'."),
    category: z.string().optional().describe("Optional main category filter, e.g. 'Restaurant', 'Hotel', 'Activity'."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results to return (1-20, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, category, limit }) => {
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const term = query.replace(/[,()*]/g, " ").trim();
    let q = supabase.from("businesses").select(
      "id, name, slug, main_category, city, neighborhood, hook_fr, hook_en, computed_rating, total_review_count, min_price, manual_price_range, priority_score"
    ).eq("is_active", true).or(
      `name.ilike.%${term}%,description.ilike.%${term}%,main_category.ilike.%${term}%,neighborhood.ilike.%${term}%,categories.cs.{"${term}"},keywords.cs.{"${term}"}`
    ).order("priority_score", { ascending: false, nullsFirst: false }).limit(Math.min(limit ?? 10, 20));
    if (city) q = q.ilike("city", `%${city}%`);
    if (category) q = q.ilike("main_category", `%${category}%`);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const results = (data ?? []).map((b) => ({
      name: b.name,
      city: b.city,
      neighborhood: b.neighborhood,
      category: b.main_category,
      rating: b.computed_rating,
      review_count: b.total_review_count,
      price_range: b.manual_price_range ?? (b.min_price ? `from ${b.min_price} MAD` : null),
      hook: b.hook_fr ?? b.hook_en,
      url: b.slug ? `https://oneworldmorocco.com/${b.slug}` : null
    }));
    return {
      content: [
        {
          type: "text",
          text: results.length ? JSON.stringify(results, null, 2) : "No businesses found for this query."
        }
      ],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-business.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z2 } from "npm:zod@^4.3.6";
var SUPABASE_URL2 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var get_business_default = defineTool2({
  name: "get_business",
  title: "Get One World Morocco business details",
  description: "Fetch the full public details of a single One World Morocco business by its slug (from the URL, e.g. 'dar-fragrance'). Returns description, address, phone, website, hours, ratings, prices and social links.",
  inputSchema: {
    slug: z2.string().min(1).describe("Business slug from the oneworldmorocco.com URL, e.g. 'dar-fragrance'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_ANON_KEY2, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("businesses").select(
      "name, slug, main_category, categories, city, neighborhood, address, phone, whatsapp, email, website, description, hook_fr, hook_en, opening_hours, computed_rating, total_review_count, min_price, manual_price_range, languages, booking_url, reserve_now_url, menu_url, instagram_url, facebook_url, tripadvisor_url"
    ).eq("slug", slug).eq("is_active", true).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No business found with slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { business: { ...data, url: `https://oneworldmorocco.com/${data.slug}` } }
    };
  }
});

// src/lib/mcp/tools/get-business-media.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z3 } from "npm:zod@^4.3.6";
var SUPABASE_URL3 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var get_business_media_default = defineTool3({
  name: "get_business_media",
  title: "Get One World Morocco business media",
  description: "Fetch every public media asset of a One World Morocco business by slug (e.g. 'riad-dar-najat'): photo URLs with their titles and descriptions, logo, YouTube videos (id, title, thumbnail, duration, short or long), external video links, virtual tour, PDF/flipbook documents, menus and AI menu summaries. Useful to build visual mockups, moodboards or design work from real assets.",
  inputSchema: {
    slug: z3.string().min(1).describe("Business slug from the oneworldmorocco.com URL, e.g. 'riad-dar-najat'."),
    max_images: z3.number().int().min(1).max(60).optional().describe("Maximum number of photo URLs to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, max_images }) => {
    const supabase = createClient3(SUPABASE_URL3, SUPABASE_ANON_KEY3, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: business, error } = await supabase.from("businesses").select(
      "id, name, slug, main_category, city, neighborhood, logo_url, logo_2_url, images, popup_image_url, video_1_url, youtube_url, vimeo_url, matterport_url, flipbook_url, pdf_url, pdf_2_url, pdf_3_url, menu_url"
    ).eq("slug", slug).eq("is_active", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!business) {
      return {
        content: [{ type: "text", text: `No active business found with slug '${slug}'.` }],
        isError: true
      };
    }
    const limit = max_images ?? 30;
    const [titlesRes, videosRes, docsRes, summariesRes] = await Promise.all([
      supabase.from("business_image_titles").select("image_url, title, description, title_en, description_en").eq("business_id", business.id),
      supabase.from("business_youtube_videos").select("video_id, title, thumbnail, custom_thumbnail_url, duration_seconds, is_short, published_at, sort_order").eq("business_id", business.id).eq("is_visible", true).order("sort_order", { ascending: true }),
      supabase.from("business_documents").select("type, name, url, language, description, thumbnail_url, price, price_type, sort_order").eq("business_id", business.id).order("sort_order", { ascending: true }),
      supabase.from("business_menu_summaries").select("title, content, avg_price_range, price_details, sort_order").eq("business_id", business.id).order("sort_order", { ascending: true })
    ]);
    const titleByUrl = /* @__PURE__ */ new Map();
    for (const row of titlesRes.data ?? []) {
      titleByUrl.set(row.image_url, {
        title: row.title ?? row.title_en ?? null,
        description: row.description ?? row.description_en ?? null
      });
    }
    const images = (Array.isArray(business.images) ? business.images : []).filter((u) => typeof u === "string" && u.length > 0).slice(0, limit).map((url, index) => ({
      position: index + 1,
      url,
      title: titleByUrl.get(url)?.title ?? null,
      description: titleByUrl.get(url)?.description ?? null
    }));
    const youtubeVideos = (videosRes.data ?? []).map((v) => ({
      video_id: v.video_id,
      title: v.title,
      thumbnail: v.custom_thumbnail_url ?? v.thumbnail ?? null,
      duration_seconds: v.duration_seconds,
      is_short: v.is_short,
      published_at: v.published_at,
      watch_url: `https://www.youtube.com/watch?v=${v.video_id}`
    }));
    const payload = {
      business: {
        name: business.name,
        slug: business.slug,
        main_category: business.main_category,
        city: business.city,
        neighborhood: business.neighborhood,
        url: `https://oneworldmorocco.com/${business.slug}`
      },
      logo: { primary: business.logo_url ?? null, secondary: business.logo_2_url ?? null },
      popup_image_url: business.popup_image_url ?? null,
      images_count: Array.isArray(business.images) ? business.images.length : 0,
      images,
      youtube_channel_url: business.youtube_url ?? null,
      youtube_videos: youtubeVideos,
      external_videos: [business.video_1_url, business.vimeo_url].filter(Boolean),
      virtual_tour_url: business.matterport_url ?? null,
      documents: (docsRes.data ?? []).map((d) => ({
        type: d.type,
        name: d.name,
        url: d.url,
        language: d.language,
        description: d.description,
        thumbnail_url: d.thumbnail_url,
        price: d.price,
        price_type: d.price_type
      })),
      flipbook_url: business.flipbook_url ?? null,
      pdfs: [business.pdf_url, business.pdf_2_url, business.pdf_3_url].filter(Boolean),
      menu_url: business.menu_url ?? null,
      menu_summaries: summariesRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-business-relations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z4 } from "npm:zod@^4.3.6";
var SUPABASE_URL4 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY4 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var get_business_relations_default = defineTool4({
  name: "get_business_relations",
  title: "Get related POIs, destinations and events for a business",
  description: "For a One World Morocco business (by slug), return the linked points of interest (nearby attractions), destinations (tourist zones), and events. Use to answer 'what's around', 'what's happening at', 'which zone' questions.",
  inputSchema: {
    slug: z4.string().min(1).describe("Business slug from the oneworldmorocco.com URL, e.g. 'dar-fragrance'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient4(SUPABASE_URL4, SUPABASE_ANON_KEY4, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: biz, error: bizErr } = await supabase.from("businesses").select("id, name, slug, city, neighborhood").eq("slug", slug).eq("is_active", true).maybeSingle();
    if (bizErr) return { content: [{ type: "text", text: `Error: ${bizErr.message}` }], isError: true };
    if (!biz) return { content: [{ type: "text", text: `No business found with slug '${slug}'.` }], isError: true };
    const [poiLinks, destLinks, evtLinks] = await Promise.all([
      supabase.from("business_poi_businesses").select("poi_business_id").eq("business_id", biz.id),
      supabase.from("business_destinations").select("destination_id").eq("business_id", biz.id),
      supabase.from("event_businesses").select("event_id").eq("business_id", biz.id)
    ]);
    const poiIds = (poiLinks.data || []).map((r) => r.poi_business_id).filter(Boolean);
    const destIds = (destLinks.data || []).map((r) => r.destination_id).filter(Boolean);
    const evtIds = (evtLinks.data || []).map((r) => r.event_id).filter(Boolean);
    const [poisRes, destsRes, evtsRes] = await Promise.all([
      poiIds.length ? supabase.from("points_of_interest").select("id, name_fr, latitude, longitude, wikipedia_fr, official_site_fr, hook").in("id", poiIds) : Promise.resolve({ data: [] }),
      destIds.length ? supabase.from("destinations").select("id, name_fr, region, latitude, longitude, wikipedia_fr, hook_fr").in("id", destIds) : Promise.resolve({ data: [] }),
      evtIds.length ? supabase.from("events").select("id, name, hook, start_date, end_date, start_time, end_time, recurrence, days_of_week, url, latitude, longitude").in("id", evtIds) : Promise.resolve({ data: [] })
    ]);
    const payload = {
      business: {
        name: biz.name,
        slug: biz.slug,
        city: biz.city,
        neighborhood: biz.neighborhood,
        url: `https://oneworldmorocco.com/${biz.slug}`
      },
      nearby_attractions: (poisRes.data || []).map((p) => ({
        name: p.name_fr,
        latitude: p.latitude,
        longitude: p.longitude,
        wikipedia: p.wikipedia_fr,
        official_site: p.official_site_fr,
        hook: p.hook
      })),
      destinations: (destsRes.data || []).map((d) => ({
        name: d.name_fr,
        region: d.region,
        latitude: d.latitude,
        longitude: d.longitude,
        wikipedia: d.wikipedia_fr,
        hook: d.hook_fr
      })),
      events: (evtsRes.data || []).map((ev) => ({
        name: ev.name,
        hook: ev.hook,
        start_date: ev.start_date,
        end_date: ev.end_date,
        start_time: ev.start_time,
        end_time: ev.end_time,
        recurrence: ev.recurrence,
        days_of_week: ev.days_of_week,
        url: ev.url
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-businesses-near-poi.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z5 } from "npm:zod@^4.3.6";
var SUPABASE_URL5 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY5 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var list_businesses_near_poi_default = defineTool5({
  name: "list_businesses_near_poi",
  title: "List One World Morocco businesses linked to a POI",
  description: "For a given point of interest name (e.g. 'Jemaa el-Fna', 'Jardin Majorelle', 'Skala de la Kasbah'), return the curated businesses explicitly linked to that POI (walking distance / cluster). Use for 'near / around / next to <landmark>' questions.",
  inputSchema: {
    poi: z5.string().min(1).describe("POI name (French). Fuzzy match on `points_of_interest.name_fr`."),
    limit: z5.number().int().min(1).max(30).optional().describe("Max businesses (1-30, default 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ poi, limit }) => {
    const supabase = createClient5(SUPABASE_URL5, SUPABASE_ANON_KEY5, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: pois, error: poiErr } = await supabase.from("points_of_interest").select("id, name_fr, city_id, latitude, longitude, wikipedia_fr").ilike("name_fr", `%${poi}%`).limit(3);
    if (poiErr) return { content: [{ type: "text", text: `Error: ${poiErr.message}` }], isError: true };
    if (!pois || !pois.length) {
      return { content: [{ type: "text", text: `No POI matching '${poi}'.` }], isError: true };
    }
    const poiIds = pois.map((p) => p.id);
    const { data: links, error: linkErr } = await supabase.from("business_poi_businesses").select("business_id, poi_business_id").in("poi_business_id", poiIds);
    if (linkErr) return { content: [{ type: "text", text: `Error: ${linkErr.message}` }], isError: true };
    const bizIds = [...new Set((links || []).map((l) => l.business_id))];
    if (!bizIds.length) {
      return {
        content: [{ type: "text", text: `POI found but no linked businesses.` }],
        structuredContent: { poi: pois[0].name_fr, results: [], count: 0 }
      };
    }
    const { data: biz, error: bizErr } = await supabase.from("businesses").select("name, slug, main_category, city, neighborhood, hook_fr, hook_en, computed_rating, total_review_count, min_price, manual_price_range, priority_score").in("id", bizIds).eq("is_active", true).order("priority_score", { ascending: false, nullsFirst: false }).limit(Math.min(limit ?? 15, 30));
    if (bizErr) return { content: [{ type: "text", text: `Error: ${bizErr.message}` }], isError: true };
    const results = (biz || []).map((b) => ({
      name: b.name,
      category: b.main_category,
      city: b.city,
      neighborhood: b.neighborhood,
      rating: b.computed_rating,
      review_count: b.total_review_count,
      price_range: b.manual_price_range ?? (b.min_price ? `from ${b.min_price} MAD` : null),
      hook: b.hook_fr ?? b.hook_en,
      url: b.slug ? `https://oneworldmorocco.com/${b.slug}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ poi: pois[0].name_fr, results }, null, 2) }],
      structuredContent: { poi: pois[0].name_fr, results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/list-blog-articles.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z6 } from "npm:zod@^4.3.6";
var SUPABASE_URL6 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY6 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var list_blog_articles_default = defineTool6({
  name: "list_blog_articles",
  title: "List One World Morocco blog articles",
  description: "List the published One World Morocco editorial articles (slug, title, excerpt, URL). Optionally filter by free-text on the title. Use it to find the slug to pass to `get_blog_article`.",
  inputSchema: {
    query: z6.string().optional().describe("Optional free-text filter on the title or slug."),
    limit: z6.number().int().min(1).max(50).optional().describe("Max articles to return (1-50, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient6(SUPABASE_URL6, SUPABASE_ANON_KEY6, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("blog_posts").select("slug, title_fr, title_en, excerpt_fr, published_at, updated_at").eq("is_published", true).order("published_at", { ascending: false, nullsFirst: false }).limit(Math.min(limit ?? 25, 50));
    if (query) {
      q = q.or(`title_fr.ilike.%${query}%,title_en.ilike.%${query}%,slug.ilike.%${query}%`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const results = (data ?? []).map((p) => ({
      slug: p.slug,
      title: p.title_fr ?? p.title_en,
      excerpt: p.excerpt_fr,
      published_at: p.published_at,
      updated_at: p.updated_at,
      url: `https://oneworldmorocco.com/blog/${p.slug}`
    }));
    return {
      content: [
        {
          type: "text",
          text: results.length ? JSON.stringify(results, null, 2) : "No published article found."
        }
      ],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-blog-article.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z7 } from "npm:zod@^4.3.6";
var SUPABASE_URL7 = "https://plnphgdrawpsnumnejzc.supabase.co";
var SUPABASE_ANON_KEY7 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbnBoZ2RyYXdwc251bW5lanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNjA5ODcsImV4cCI6MjA4NTgzNjk4N30.RwHKmL6E0Gd2LTVvDkfYx5RkZ-k7LKKp4iUoCS34pW4";
var get_blog_article_default = defineTool7({
  name: "get_blog_article",
  title: "Read a One World Morocco blog article",
  description: "Read the full public content of a One World Morocco editorial article (blog) by slug, or by free-text title search. Returns title, TL;DR, intro, every ranked entry (pretitle, title, paragraphs, opening hours), FAQ and the public URL. Example slug: 'idee-cadeau-marrakech' for the article 'Trouver une bonne id\xE9e cadeau \xE0 Marrakech'.",
  inputSchema: {
    slug: z7.string().optional().describe("Article slug from the URL, e.g. 'idee-cadeau-marrakech'."),
    query: z7.string().optional().describe("Free-text search on the article title if the slug is unknown, e.g. 'id\xE9e cadeau'."),
    lang: z7.enum(["fr", "en", "ar"]).optional().describe("Language of the content to return (default 'fr').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, query, lang }) => {
    if (!slug && !query) {
      return {
        content: [{ type: "text", text: "Provide either `slug` or `query`." }],
        isError: true
      };
    }
    const l = lang ?? "fr";
    const supabase = createClient7(SUPABASE_URL7, SUPABASE_ANON_KEY7, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("blog_posts").select(
      "slug, title_fr, title_en, title_ar, excerpt_fr, excerpt_en, excerpt_ar, tldr_fr, tldr_en, tldr_ar, intro_fr, intro_en, intro_ar, entries_fr, entries_en, entries_ar, faq_fr, faq_en, faq_ar, author_name, published_at, updated_at, cover_image_url"
    ).eq("is_published", true).limit(1);
    q = slug ? q.eq("slug", slug) : q.or(
      `title_fr.ilike.%${query}%,title_en.ilike.%${query}%,slug.ilike.%${query}%`
    );
    const { data, error } = await q.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [
          { type: "text", text: `No published blog article found for '${slug ?? query}'.` }
        ],
        isError: true
      };
    }
    const pick = (base) => data[`${base}_${l}`] ?? data[`${base}_fr`] ?? null;
    const rawEntries = pick("entries") ?? [];
    const entries = (Array.isArray(rawEntries) ? rawEntries : []).map((e, i) => {
      const entry = e ?? {};
      return {
        rank: i + 1,
        pretitle: entry.pretitle ?? null,
        title: entry.title ?? null,
        paragraphs: entry.paragraphs ?? null,
        hours: entry.hours ?? null
      };
    });
    const payload = {
      slug: data.slug,
      lang: l,
      title: pick("title"),
      excerpt: pick("excerpt"),
      tldr: pick("tldr"),
      intro: pick("intro"),
      author: data.author_name,
      published_at: data.published_at,
      updated_at: data.updated_at,
      cover_image_url: data.cover_image_url,
      url: `https://oneworldmorocco.com/blog/${data.slug}`,
      entries_count: entries.length,
      entries,
      faq: pick("faq")
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "one-world-morocco",
  title: "One World Morocco",
  version: "0.4.0",
  instructions: "Public read-only access to the One World Morocco catalog and editorial blog: curated restaurants, hotels, riads, activities and boutiques in Marrakech, Essaouira and across Morocco. Tools: `search_businesses` (free-text search), `get_business` (full details by slug), `get_business_media` (all photos with titles, logo, YouTube videos, virtual tour, menus and documents by slug), `get_business_relations` (linked POIs, destinations, events for a business), `list_businesses_near_poi` (businesses tied to a landmark like Jemaa el-Fna or Jardin Majorelle), `list_blog_articles` (published editorial articles) and `get_blog_article` (full article content by slug, e.g. 'idee-cadeau-marrakech'). All data is public \u2014 no personal or member data is exposed.",
  tools: [
    search_businesses_default,
    get_business_default,
    get_business_media_default,
    get_business_relations_default,
    list_businesses_near_poi_default,
    list_blog_articles_default,
    get_blog_article_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
