
ALTER TABLE public.labels
  ADD COLUMN IF NOT EXISTS show_on_home BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_on_category BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_on_city BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_on_service BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_on_neighborhood BOOLEAN NOT NULL DEFAULT false;
