
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS tldr_fr TEXT,
  ADD COLUMN IF NOT EXISTS tldr_en TEXT,
  ADD COLUMN IF NOT EXISTS tldr_ar TEXT,
  ADD COLUMN IF NOT EXISTS faq_fr JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faq_en JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faq_ar JSONB DEFAULT '[]'::jsonb;
